name: MATLAB actions test
on:
  workflow_dispatch:
jobs:
  run-matlab-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run tests
        uses: matlab-actions/run-tests@v2
