name: MATLAB actions test
on:
  workflow_dispatch:
jobs:
  test-matlab-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: MATLAB
  name: Run MATLAB Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run tests
        uses: matlab-actions/run-tests@v2
